version: "3"

services:
  myapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - "./app:/app"
      - "./app/staticfiles:/app/staticfiles"
    env_file:
      - ./.env.dev
    depends_on:
      - postgresql
    restart: "on-failure"

  adminer:
    image: adminer
    ports:
      - "8002:8080"
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=postgresql

  postgresql:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_dj
      - POSTGRES_PASSWORD=password0x
      - POSTGRES_DB=mydj_dev

volumes:
  pg_data: